cancer = rnorm(15, 1.5)
healthy = 1
hist(cancer)
abline(v=healthy, col="red")
table(cancer > healthy)
binom.prod = function(s,n,p) choose(n, s)*p^s*(1-p)^(n-s)
binom.prod(5,15,0.5)
sapply(0:5, function(i) binom.prod(i, 15, 05))
sum(sapply(0:5, function(i) binom.prod(i,15,0.5)))
dbinom(0:5,15,0.5)
sum(dbinom(0:5, 15, 0.5))
pbinom(5,15,0.5)
pbinom(5,15,0.5)*2
binom.test(5, 15, 0.5)
binom.test(5, 15, 0.5, a='l')
healthy=rnorm(15,1)
ustat=function(x,y) sum(sapply(x,function(i)sum(i>y)))
ustat(healthy,cancer)
ustat(cancer,healthy)
wilcox.test(cancer,healthy)
mean(cancer)-mean(healthy)
# permutation test
t.test(cancer, healthy, alternative = "g")
